version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "friday"
    labels:
      - "part:tooling"
      - "type:tech-debt"
    # Default versioning-strategy. For other versioning-strategy see:
    # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#versioning-strategy
    versioning-strategy: auto
    # Allow up to 10 open pull requests for updates to dependency versions
    open-pull-requests-limit: 10
    # We group production and development ("optional" in the context of
    # pyproject.toml) dependency updates when they are patch and minor updates,
    # so we end up with less PRs being generated.
    # Major updates are still managed, but they'll create one PR per
    # dependency, as major updates are expected to be breaking, it is better to
    # manage them individually.
    groups:
      required:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      optional:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "friday"
    labels:
      - "part:tooling"
      - "type:tech-debt"
