# MkDocs configuration
# For details see: https://www.mkdocs.org/user-guide/configuration/

# Project information
site_name: Frequenz Python SDK
site_description: Frequenz Python SDK.
site_author: Frequenz Energy-as-a-Service GmbH
copyright: Frequenz Energy-as-a-Service GmbH
repo_name: "frequenz-sdk-python"
repo_url: "https://github.com/frequenz-floss/frequenz-sdk-python"
edit_uri: "edit/v0.x.x/docs/"

# Build directories
theme:
  name: "material"
  logo: logo.png
  favicon: logo.png
  language: en
  icon:
    edit: material/file-edit-outline
    repo: fontawesome/brands/github
  custom_dir: docs/overrides
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - toc.follow
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: indigo
    accent: deep purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: teal
    toggle:
      icon: material/weather-night
      name: Switch to light mode

extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/frequenz-floss
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/company/frequenz-com
  version:
    provider: mike
    default: latest

extra_css:
  - css/style.css
  - css/mkdocstrings.css

# Formatting options
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tabbed
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: "!!python/name:pymdownx.superfences.fence_code_format"
  - toc:
      permalink: "Â¤"

plugins:
  - gen-files:
      scripts:
        - docs/mkdocstrings_autoapi.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mike:
      canonical_version: latest
  - mkdocstrings:
      custom_templates: templates
      default_handler: python
      handlers:
        python:
          options:
            paths: [src]
            docstring_section_style: spacy
            merge_init_into_class: false
            show_category_heading: true
            show_root_heading: true
            show_root_members_full_path: true
            show_source: true
          import:
            - https://docs.python.org/3/objects.inv
  - search
  - section-index

# Preview controls
watch:
  - src
  - README.md
  - CONTRIBUTING.md
