name: Pull Request Labeler

on: [pull_request_target]

jobs:
  Label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Labeler
        # XXX: !!! SECURITY WARNING !!!
        # pull_request_target has write access to the repo, and can read secrets. We
        # need to audit any external actions executed in this workflow and make sure no
        # checked out code is run (not even installing dependencies, as installing
        # dependencies usually can execute pre/post-install scripts). We should also
        # only use hashes to pick the action to execute (instead of tags or branches).
        # For more details read:
        # https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
        uses: actions/labeler@ac9175f8a1f3625fd0d4fb234536d26811351594  # 4.3.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
