name: Release Notes Check

on:
  merge_group:
  pull_request:
    types:
      # On by default if you specify no types.
      - "opened"
      - "reopened"
      - "synchronize"
      # For `skip-label` only.
      - "labeled"
      - "unlabeled"


jobs:
  check-release-notes:
    name: Check release notes are updated
    runs-on: ubuntu-latest
    steps:
      - name: Check for a release notes update
        if: github.event_name == 'pull_request'
        uses: brettcannon/check-for-changed-files@4170644959a21843b31f1181f2a1761d65ef4791 # v1.2.0
        with:
          file-pattern: "RELEASE_NOTES.md"
          prereq-pattern: "src/**"
          skip-label: "cmd:skip-release-notes"
          failure-message: "Missing a release notes update. Please add one or apply the ${skip-label} label to the pull request"
